kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ingress-controller
nodes:
- role: control-plane
  image: kindest/node:v1.24.2
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30200
  - containerPort: 30001
    hostPort: 30201
  - containerPort: 30002
    hostPort: 30202
- role: worker
  image: kindest/node:v1.24.2
- role: worker
  image: kindest/node:v1.24.2
